### ISSUE TITLE
Switch sf2d to citro3d

### ISSUE THREAD

**Issue by xerpi** [Magicrafter13/Breakout#1]
libsf2d is deprecated, [citro3d](https://github.com/fincs/citro3d) should be used instead. Check [this](https://github.com/devkitPro/3ds-examples/tree/master/graphics/gpu/gpusprites) sample.

EDIT: There's also [this](https://github.com/BernardoGiordano/pp2d) lib which, albeit not official, it isn't deprecated.

**Comment by Magicrafter13** [comment]
citro3d supports 2d games?

**Comment by Magicrafter13** [comment]
Oh, well reading something in the main.c of that example, I often use Citra to quickly test something so I don't have to pull out my 3ds, so not being able to emulate on Citra would kinda suck :/ though it says immediate mode, so I assume the VBO mode works on Citra then? I mean either way I don't know what that stuff is but as long as I can just copy the code from the example with only minor changes then I guess it wouldn't be hard to switch over.

EDIT: Even the example looks really complicated to me. Is there really anything wrong with using sf2d for now? I mean it works well enough for me.

**Comment by Magicrafter13** [comment]
Okay I didn't switch purely to citro3d, I switched to that pp2d.
And it was surprisingly similar to your sf2d, so I had no trouble :)
